-- Assignment 7 - SalesComp (5 SELECT Queries)

-- 1. Invoices with customer names
SELECT 
    C.CUST_CODE,
    C.CUST_FNAME,
    C.CUST_LNAME,
    I.INV_NUMBER,
    SUM(L.LINE_NUMBER * L.LINE_PRICE) AS TOTAL
FROM CUSTOMER C
JOIN INVOICE I ON C.CUST_CODE = I.CUST_CODE
JOIN LINE L ON I.INV_NUMBER = L.INV_NUMBER
GROUP BY 
    C.CUST_CODE,
    C.CUST_FNAME,
    C.CUST_LNAME,
    I.INV_NUMBER
ORDER BY C.CUST_CODE, I.INV_NUMBER;

-- 2. Products with vendor names
SELECT 
    I.INV_NUMBER,
    L.LINE_NUMBER,
    L.PROD_CODE,
    P.PROD_DESCRIPT,
    L.LINE_UNITS,
    L.LINE_PRICE,
    (L.LINE_UNITS * L.LINE_PRICE) AS LINE_TOTAL
FROM INVOICE I
JOIN LINE L ON I.INV_NUMBER = L.INV_NUMBER
JOIN PRODUCT P ON L.PROD_CODE = P.PROD_CODE
WHERE I.CUST_CODE = 10011
ORDER BY I.INV_NUMBER, L.LINE_NUMBER;

-- 3. Line items with product info
SELECT 
    V.VEND_CODE,
    V.VEND_NAME,
    V.VEND_CONTACT,
    V.VEND_PHONE,
    V.VEND_STATE
FROM VENDOR V
WHERE V.VEND_AREACODE = 615 
OR V.VEND_STATE = 'TN';

-- 4. Full invoice breakdown (customer + products)
SELECT 
    P.PROD_CODE,
    P.PROD_DESCRIPT,
    P.PROD_INDATE,
    P.PROD_QOH,
    P.PROD_MIN
FROM PRODUCT P
WHERE P.PROD_QOH <= P.PROD_MIN + 5;

-- 5. Customers and their invoices (including those with none)
SELECT 
    P.PROD_CODE,
    P.PROD_DESCRIPT,
    P.PROD_INDATE,
    P.PROD_QOH
FROM PRODUCT P
WHERE P.PROD_CODE NOT IN (
    SELECT DISTINCT PROD_CODE FROM LINE
)