-- Assignment 7 code begins here
CREATE TABLE Customer (
    CUST_CODE INTEGER PRIMARY KEY,
    CUST_LNAME VARCHAR(50) NOT NULL,
    CUST_FNAME VARCHAR(50) NOT NULL,
    CUST_INITIAL VARCHAR(1),
    CUST_AREACODE VARCHAR(3) NOT NULL,
    CUST_PHONE VARCHAR(8) NOT NULL,
    CUST_BALANCE REAL NOT NULL
);

CREATE TABLE Invoice (
    INV_NUMBER INTEGER PRIMARY KEY,
    CUST_CODE INTEGER NOT NULL,
    INV_DATE VARCHAR(20) NOT NULL,
    FOREIGN KEY (CUST_CODE) REFERENCES Customer(CUST_CODE)
);

CREATE TABLE Vendor (
    VEND_CODE INTEGER PRIMARY KEY,
    VEND_NAME VARCHAR(100) NOT NULL,
    VEND_CONTACT VARCHAR(50) NOT NULL,
    VEND_AREACODE VARCHAR(3) NOT NULL,
    VEND_PHONE VARCHAR(8) NOT NULL,
    VEND_STATE VARCHAR(2) NOT NULL,
    VEND_ORDER VARCHAR(1) NOT NULL
);

CREATE TABLE Product (
    PROD_CODE VARCHAR(25) PRIMARY KEY,
    PROD_DESCRIPT VARCHAR(100) NOT NULL,
    PROD_INDATE VARCHAR(20) NOT NULL,
    PROD_QOH INTEGER NOT NULL,
    PROD_MIN INTEGER NOT NULL,
    PROD_PRICE REAL NOT NULL,
    PROD_DISCOUNT REAL NOT NULL,
    VEND_CODE INTEGER,
    FOREIGN KEY (VEND_CODE) REFERENCES Vendor(VEND_CODE)
);

CREATE TABLE Line (
    INV_NUMBER INTEGER NOT NULL,
    LINE_NUMBER INTEGER NOT NULL,
    PROD_CODE VARCHAR(25) NOT NULL,
    LINE_UNITS INTEGER NOT NULL,
    LINE_PRICE REAL NOT NULL,
    PRIMARY KEY (INV_NUMBER, LINE_NUMBER),
    FOREIGN KEY (INV_NUMBER) REFERENCES Invoice(INV_NUMBER),
    FOREIGN KEY (PROD_CODE) REFERENCES Product(PROD_CODE)
);


