CREATE TABLE Computer (
    CompID VARCHAR(50) PRIMARY KEY,
    MfgName VARCHAR(100) NOT NULL,
    MFGModel VARCHAR(50) NOT NULL,
    ProcType VARCHAR(50) NOT NULL
);

CREATE TABLE Employee (
    EmpNum INTEGER PRIMARY KEY,
    EmpFirst VARCHAR(50) NOT NULL,
    EmpLast VARCHAR(50) NOT NULL,
    EmpPhone VARCHAR(20) NOT NULL
);

CREATE TABLE Package (
    PackID VARCHAR(50) PRIMARY KEY,
    PackName VARCHAR(100) NOT NULL,
    PackVers VARCHAR(50) NOT NULL,
    PackType VARCHAR(50) NOT NULL,
    PackCost REAL NOT NULL
);

CREATE TABLE PC (
    TagNum INTEGER PRIMARY KEY,
    CompID VARCHAR(50) NOT NULL,
    EmpNum INTEGER NOT NULL,
    Location VARCHAR(50) NOT NULL,
    FOREIGN KEY (CompID) REFERENCES Computer(CompID),
    FOREIGN KEY (EmpNum) REFERENCES Employee(EmpNum)
);

CREATE TABLE Software (
    PackID VARCHAR(50) NOT NULL,
    TagNum INTEGER NOT NULL,
    InstDate VARCHAR(20) NOT NULL,
    SoftCost REAL NOT NULL,
    PRIMARY KEY (PackID, TagNum),
    FOREIGN KEY (PackID) REFERENCES Package(PackID),
    FOREIGN KEY (TagNum) REFERENCES PC(TagNum)
);